---

- hosts: zabbix-servers
  become: yes

  vars:
    zabbix_server_ip: 10.129.0.12

  tasks:

  - name: install repo zabbix for Ubuntu
    apt:
      deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
      state: present
    when:
      ansible_os_family == "Debian"

  - name: install repo zabbix for Centos
    yum:
      name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      state: present
    when:
      ansible_os_family == "RedHat"

  - name: install zabbix-agent for Ubuntu
    apt:
      name=zabbix-agent
    when:
      ansible_os_family == "Debian"

  - name: install repo zabbix for Centos
    yum:
      name=zabbix-agent
    when:
      ansible_os_family == "RedHat"

  - name: "Make sure the zabbix-agent service is running"
    service:
      name: zabbix-agent
      state: started
      enabled: yes
    become: yes

  - name: add a Hostname to the zabbix-agent-config and delete the default from before
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf
              regexp='# Hostname='
              line='Hostname={{ ansible_hostname }}'
              state=present

  - name: add a Server to the zabbix-agent-config and delete the dafault from before
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf
              regexp='^Server=127.0.0.1'
              line='Server={{ zabbix_server_ip }}'
              state=present

  - name: add a ServerActive to the zabbix-agent-config and delete the default from before
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf
              regexp='^ServerActive=127.0.0.1'
              line='ServerActive={{ zabbix_server_ip }}'
              state=present

  - name: restart zabbix-agent
    service:
      name: zabbix-agent
      state: restarted
      enabled: yes
    become: yes
